#!/bin/bash

# Script d'installation postérieure (postinst) pour le paquet AppImageBuilder

# Variables pour les chemins du script et des raccourcis
script_path="/usr/bin/AppImageBuilderGUI"
desktop_file_path="/usr/share/applications/AppImageBuilderGUI.desktop"

# Mettre le script en exécution
chmod +x "$script_path"

# Mettre à jour GTK (les commandes peuvent varier en fonction de la distribution)
if command -v apt-get &>/dev/null; then
  apt-get update
  apt-get install --reinstall libgtk-3-0
elif command -v dnf &>/dev/null; then
  dnf upgrade gtk3
elif command -v yum &>/dev/null; then
  yum upgrade gtk3
elif command -v pacman &>/dev/null; then
  pacman -Syu gtk3
fi

# Créer le raccourci .desktop sur le bureau
echo "[Desktop Entry]
Version=2.5
Type=Application
Name=AppImageBuilder
Exec=$script_path %U
Terminal=false
Categories=Utility;" > "$desktop_file_path"

# Donner l'autorisation d'exécution au fichier de raccourci .desktop
chmod +x "$desktop_file_path"

# Sortir avec un statut de succès
exit 0
